### ISSUE TITLE
How to monitor MySQL running on the same machine as php?

### ISSUE THREAD

**Issue by uptop-adelgado** [packetbeat/packetbeat#105]
I have a machine running both the app server and mysql, mysql is listening on 127.0.0.1

Can I use packetbeat to capture traffic in between the appserver and the database?

I've tried using tcpdump -i lo but it doesn't capture those requests...

**Comment by uptop-adelgado** [comment]
a quick update, I kinda figured outm but i would like to know if there are better options:

PHP is using localhost to connect, and that ends up using a socket to connect to the DB, if I ask PHP to connect using 127.0.0.1 it uses the networking stack, and then I can capture the data, but there's a small price to pay for that.

Is there a way packetbeat can listen in on the unix socket?

**Comment by tsg** [comment]
Hi, unfortunately there's no practical way to listen on the unix socket.
