### ISSUE TITLE
Kibana 4?

### ISSUE THREAD

**Issue by NeckBeardPrince** [packetbeat/packetbeat#108]
Last thread on this said it would be released in a few days.. any update?

**Comment by tsg** [comment]
Sorry for the delay, we had a change in plans regarding the release. We're working on it, it shouldn't take much longer.

**Comment by proffalken** [comment]
I'm also looking forward to this because I need to fix https://github.com/packetbeat/dashboards/issues/6 :)

**Comment by tsg** [comment]
We finally published [v0.5.0](https://github.com/packetbeat/packetbeat/releases/tag/v0.5.0) and also Kibana4 dashboards to go with it. Here is how you can load the Kibana 4 dashboards:

    curl -L -O https://github.com/packetbeat/dashboards/archive/v0.5.0.tar.gz
    tar xzvf  v0.5.0.tar.gz
    cd dashboards-0.5.0/
    ./load.sh http://<elasticsearch-url>
