### ISSUE TITLE
How can I configure Packetbeat to send HTTP body?

### ISSUE THREAD

**Issue by mingfang** [packetbeat/packetbeat#110]
The default configuration sends only the request line but no body.

**Comment by tsg** [comment]
Which version are you using? For 0.4.3, the complete HTTP headers as read from the message are stored in "requests_raw" and "response_raw" fields by default. If you want to include the body of the messages, you can do that selectively by content-type with something like this:

    [http]
    include_body_for = ["text/html", "application/json"]

**Comment by mingfang** [comment]
that worked. thank you!

**Comment by mingfang** [comment]
I just installed v0.5.0 and the option to include http body appears broken.

**Comment by tsg** [comment]
It's probably because we flipped the default values for the `send_request` and `send_response` options. Here is a minimal configuration that I tried and works:

    [protocols]
      [protocols.http]
      ports = [80, 8080, 8000, 5000, 8002]
      send_request = true
      send_response = true

    [http]
    include_body_for=["text/html"]

Take care that the `send_request` and `send_response` options should go into the `[protocols.http]` section, not into the `[http]` one.

**Comment by mingfang** [comment]
Yes I just discovered this as well.  Thanks for the update.

**Comment by mingfang** [comment]
In case anyone is interested, I have the Packetbeat Agent with theses settings inside a Docker container here https://github.com/mingfang/docker-packetbeat-agent.
And the companion dashboard is here https://github.com/mingfang/docker-packetbeat

**Comment by tsg** [comment]
Nice! thanks for sharing
