### ISSUE TITLE
Can I know where are we using packetbeat-topology index?

### ISSUE THREAD

**Issue by harshamadala** [packetbeat/packetbeat#113]
I have seen kibana dashboard, which is determining map based on src_server and dst_server using kibana force panel. Could any one please point me on how to use this topology or direct me if we are using it anywhere?

**Comment by tsg** [comment]
The `packetbeat-topology` index is used internally to compute the values for `src_server` and `dst_server`. Imagine that you have an agent installed on HostA and an agent installed on HostB, if a message goes from HostA to HostB, and it is seen by the agent on HostA, that agent somehow needs to know which IP addresses are on HostB. That's done by communicating via this special index.
