### ISSUE TITLE
Ansible error

### ISSUE THREAD

**Issue by bscott** [packetbeat/packetbeat#116]
Packetbeat 0.5.0 RPM does not exist in Github Releases Downloads

failed: [54.92.240.89] => {"changed": false, "failed": true, "rc": 1}
msg: Package at https://github.com/packetbeat/packetbeat/releases/download/v0.5.0/packetbeat-0.5.0-1.el6.x86_64.rpm could not be installed

**Comment by tsg** [comment]
Closing this one in favor of https://github.com/packetbeat/packetbeat-deploy/issues/9
