### ISSUE TITLE
World Map not saving field setting

### ISSUE THREAD

**Issue by bscott** [packetbeat/packetbeat#117]
I'm trying to update my map to use src_country, but after saving and returning to the setting, it reverts to just "src". I'm using 0.4.3 of PacketBeat.

![image](https://cloud.githubusercontent.com/assets/191290/7104747/684f1b92-e0ab-11e4-818f-d4a0e1b795dc.png)

**Comment by tsg** [comment]
This seems to be an issue with Kibana 3. Could you try another browser, please?
