### ISSUE TITLE
Elasticsearch Field analyzed

### ISSUE THREAD

**Issue by whisk3y** [packetbeat/packetbeat#120]
I am trying to get User-Agent visualization in kibana 4 and in kibana 3. The http.request_headers.user-agent field is set to analyze. Is there anyway that field could be set to multi-field or just change analyzed to not_analyzed in the field mapping from packetbeat. 

In Kibana if i try to do a term count for User-Agents the chart takes:
"Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4" 

and displays in the table as:
"Mozilla/5.0" 

The notification from kibana4:
**Careful! The field selected contains analyzed strings. Values such as foo-bar will be broken into foo and bar. See Mapping Core Types for more information on setting this field as not_analyzed**

[The Manual process updating/reindexing the mapping](https://www.elastic.co/blog/changing-mapping-with-zero-downtime)

I do not want to go through the process for each new index.

Thanks! You guys are making a great product!

**Comment by tsg** [comment]
Hi, you can do that with the ES template that we provide. The template does exactly that, set the `not_analyzed` flag automatically for all new `packetbeat-*` indexes.

Here are the instructions to load it:

    curl -L -O 'https://raw.githubusercontent.com/packetbeat/packetbeat/v0.5.0/packetbeat.template.json'
    curl -XPUT 'http://localhost:9200/_template/packetbeat' -d@packetbeat.template.json

(these are buried somewhere in the getting started guide)

**Comment by whisk3y** [comment]
Thanks. Tudor. You are the man.
