### ISSUE TITLE
Agent not creating index

### ISSUE THREAD

**Issue by wyzbv** [packetbeat/packetbeat#121]
I'm working on getting packetbeat setup and I have the agent running on a single server that is hosting a mysql db and nginx "hello world" website.  Traffic is clearly flowing around as debugging shows things happening.

However, nothing is getting pushed to my elastic search cluster.  I have the packetbeat.conf file set as follows

[output]
  [output.elasticsearch]
    enabled = true
    host = "1.2.3.4"
    port = 9200

The .packetbeat-topology index is being created, but the [packetbeat]-YYYY.mm.dd index is not being created.  I attempted to use the template from master and from v0.5.0/packetbeat.template.json' but neither worked.  Deleting the template did not work either.  I also manually created the index (both with and without the template) and no documents are ever inserted.

There's also nothing in my es logs to indicate that packetbeat is even trying to create the index.

Anyone have any ideas?  I really want to try this out.

**Comment by tsg** [comment]
Can you try starting the agent in foreground like this:


     packetbeat -e -c /etc/packetbeat/packetbeat.conf -d "publish"

And look for errors and if anything is reported as "published". Feel free to upload the log here, I can have a look.

**Comment by wyzbv** [comment]
The only thing that looks out of the ordinary is:
http.go:714: WARN Response from unknown transaction. Ignoring: TcpTuple src[192.168.1:47153] dst[192.168.1.238:8080] stream_id[9]

output_elasticsearch.go:58: INFO [ElasticsearchOutput] Using Elasticsearch http://192.168.1.61:9200
output_elasticsearch.go:59: INFO [ElasticsearchOutput] Using index pattern [packetbeat-]YYYY.MM.DD
output_elasticsearch.go:60: INFO [ElasticsearchOutput] Topology expires after 15s
publish.go:220: INFO Using Elasticsearch to store the topology
publish.go:276: INFO No agent name configured, using hostname 'hqnix01.hq.company.net'
publish.go:289: INFO Topology map refreshed every 10s
publish.go:185: DBG  Add topology entry for hqnix01.hq.company.net: [192.168.1.238 fe80::215:5dff:fe00:b23b]
geolite.go:59: INFO Loaded GeoIP data from: /usr/share/GeoIP/GeoLiteCountry.dat
publish.go:185: DBG  Add topology entry for hqnix01.hq.company.net: [192.168.1.238 fe80::215:5dff:fe00:b23b]
http.go:714: WARN Response from unknown transaction. Ignoring: TcpTuple src[192.168.1.238:8080] dst[192.168.1.89:46647] stream_id[1]
http.go:714: WARN Response from unknown transaction. Ignoring: TcpTuple src[192.168.1.238:8080] dst[192.168.1.89:46647] stream_id[1]
publish.go:185: DBG  Add topology entry for hqnix01.hq.company.net: [192.168.1.238 fe80::215:5dff:fe00:b23b]
publish.go:185: DBG  Add topology entry for hqnix01.hq.company.net: [192.168.1.238 fe80::215:5dff:fe00:b23b]
http.go:714: WARN Response from unknown transaction. Ignoring: TcpTuple src[192.168.1.89:47149] dst[192.168.1.238:8080] stream_id[7]
http.go:714: WARN Response from unknown transaction. Ignoring: TcpTuple src[192.168.1.89:47149] dst[192.168.1.238:8080] stream_id[7]
http.go:714: WARN Response from unknown transaction. Ignoring: TcpTuple src[192.168.1.89:47153] dst[192.168.1.238:8080] stream_id[9]
http.go:714: WARN Response from unknown transaction. Ignoring: TcpTuple src[192.168.1.89:47153] dst[192.168.1.238:8080] stream_id[9]
publish.go:185: DBG  Add topology entry for hqnix01.hq.company.net: [192.168.1.238 fe80::215:5dff:fe00:b23b]
publish.go:185: DBG  Add topology entry for hqnix01.hq.company.net: [192.168.1.238 fe80::215:5dff:fe00:b23b]
^Csniffer.go:318: INFO Input finish. Processed 94 packets. Have a nice day!
[bvah@hqnix01 ~]$ sudo packetbeat -e -c /etc/packetbeat/packetbeat.conf -d "publish"
output_elasticsearch.go:58: INFO [ElasticsearchOutput] Using Elasticsearch http://192.168.1.61:9200
output_elasticsearch.go:59: INFO [ElasticsearchOutput] Using index pattern [packetbeat-]YYYY.MM.DD
output_elasticsearch.go:60: INFO [ElasticsearchOutput] Topology expires after 15s
publish.go:220: INFO Using Elasticsearch to store the topology
publish.go:276: INFO No agent name configured, using hostname 'hqnix01.hq.company.net'
publish.go:289: INFO Topology map refreshed every 10s
publish.go:185: DBG  Add topology entry for hqnix01.hq.company.net: [192.168.1.238 fe80::215:5dff:fe00:b23b]
geolite.go:59: INFO Loaded GeoIP data from: /usr/share/GeoIP/GeoLiteCountry.dat
publish.go:185: DBG  Add topology entry for hqnix01.hq.company.net: [192.168.1.238 fe80::215:5dff:fe00:b23b]
publish.go:185: DBG  Add topology entry for hqnix01.hq.company.net: [192.168.1.238 fe80::215:5dff:fe00:b23b]
publish.go:185: DBG  Add topology entry for hqnix01.hq.company.net: [192.168.1.238 fe80::215:5dff:fe00:b23b]
publish.go:185: DBG  Add topology entry for hqnix01.hq.company.net: [192.168.1.238 fe80::215:5dff:fe00:b23b]
publish.go:185: DBG  Add topology entry for hqnix01.hq.company.net: [192.168.1.238 fe80::215:5dff:fe00:b23b]

**Comment by tsg** [comment]
Then please create a short pcap dump, like this:

   packetbeat -e -c /etc/packetbeat/packetbeat.conf -dump trace.pcap

Send me that pcap file at tudor@packetbeat.com or upload it somewhere and put the link here.

**Comment by wyzbv** [comment]
Welp, it's one of those.

I started stopping a bunch of services to get you a cleaner dump and it suddenly started working.  Looks like I have a conflict somewhere on my end.  Sorry about that.

**Comment by wyzbv** [comment]
Actually, it looks like Ansible Tower is the culprit, just not sure why.

**Comment by tsg** [comment]
Hmm, that sounds strange, I don't see how Ansible Tower could be related in any way. Closing for now, reopen if you have any question.
