### ISSUE TITLE
Add log output

### ISSUE THREAD

**Issue by michaelgibson** [packetbeat/packetbeat#27]
It would be nice to be able to configure the output to just go to a log file for it's output instead of Elasticsearch directly.
As the number of systems running the agent grows, things like compression and bulk indexing become necessary. 
Those specific features "could" be coded into this application but outputting to a log would allow for other more generalized transport mechanisms to pick up the data.
i.e. logstash, heka, fluentd.

**Comment by tsg** [comment]
This is possible since that commit.

**Comment by surajsavita** [comment]
+1 to Kafka output plugin which can be used in logstash kafka input plugin to bulk insert in elasticsearch.

**Comment by EamonZhang** [comment]
+1

**Comment by biswajit86** [comment]
+1
