### ISSUE TITLE
Centos/RHEL/OEL version 5 rpms

### ISSUE THREAD

**Issue by jonesy1234** [packetbeat/packetbeat#38]
Is it possible to get a package made for release 5? Many enterprises are stuck on this version due to application certification issues. Oracle software mostly certified on OEL 5. Is it possible or not due to code features?

**Comment by bhgraham** [comment]
Was this closed because Cent5 builds are now available?  I was unable to locate them.

**Comment by andrewkroh** [comment]
The project doesn't have any official support for RHEL 5. The code is written in Go and the Go project doesn't support CentOS/RHEL 5 (they require kernel "2.6.23 or later", from [golang.org](https://golang.org/doc/install)).
