### ISSUE TITLE
Packetbeat agent not running.

### ISSUE THREAD

**Issue by Velumani-Duraisamy** [packetbeat/packetbeat#83]
Hi ,
     I am new to Packetbeat. i followed the user manual(using rpm) to install packetbeat-0.4.2 in my centos 6.6 . I didn't got any error but the packetbeat process is not running.

![image](https://cloud.githubusercontent.com/assets/9958417/5625931/211247aa-95aa-11e4-882e-0ae50e75d6ad.png)

![image](https://cloud.githubusercontent.com/assets/9958417/5625942/47482f52-95aa-11e4-8a3f-19f219266abe.png)

Someone pls help.

**Comment by rickard-von-essen** [comment]
Run packetbeat manually from the command line with verbose. It usually tells you what is wrong. Usually the is a error in the cfg.

**Comment by Velumani-Duraisamy** [comment]
Thanks rickard-von-essen . Started packetbeat agent after fixing my issue in elasticsearch.
