### ISSUE TITLE
ParseHttp exception

### ISSUE THREAD

**Issue by whisk3y** [packetbeat/packetbeat#84]
I finally got packetbeat moved to a production server for testing and got a new error in the logs. Has anyone ran into this issue? I get it every couple minutes in pairs. 

I am using the latest PB rpm to install on redhat 6.2
Only monitoring pgsql and http at the moment

<code>Jan  7 09:55:04 fwdclpwebcms03c /usr/bin/packetbeat[19810]: log_unix.go:116: ParseHttp
exception. Recovering, but please report this: runtime error: slice bounds out of range.</code>

<code>Jan  7 09:55:04 fwdclpwebcms03c /usr/bin/packetbeat[19810]: log_unix.go:117: Stacktrace: /home/vagrant/rpmbuild/BUILD/packetbeat/log_unix.go:117 (0x40baf8)#012/usr/local/go/src/pkg/runtime/panic.c:248 (0x44cf8d)#012/usr/local/go/src/pkg/runtime/panic.c:552 (0x44da3d)#012/usr/local/go/src/pkg/runtime/panic.c:472 (0x44d767)#012/home/vagrant/rpmbuild/BUILD/packetbeat/http.go:503 (0x408137)#012/home/vagrant/rpmbuild/BUILD/packetbeat/tcp.go:96 (0x42aaf6)#012/home/vagrant/rpmbuild/BUILD/packetbeat/tcp.go:209 (0x42b599)#012/home/vagrant/rpmbuild/BUILD/packetbeat/tcp.go:362 (0x42cdd5)#012/home/vagrant/rpmbuild/BUILD/packetbeat/main.go:356 (0x40e8c4)#012/usr/local/go/src/pkg/runtime/proc.c:247 (0x44efea)#012/usr/local/go/src/pkg/runtime/proc.c:1445 (0x4517b0)</code>

**Comment by tsg** [comment]
Looks like a bug where `stream.message.end` falls out of the `stream.data` slice. But that's quite strange because it was falling within it just a few lines before (line 497). Do you, by any chance, run with a custom `GOMAXPROCS` env variable?

**Comment by whisk3y** [comment]
No, we do not.

**Comment by tsg** [comment]
How often does it happen? Would it be possible to create a trace like this and then send it to me (tudor@packetbeat.com):

   packetbeat -e -c /etc/packetbeat/packetbeat.conf -dump slice_error.pcap

Leave it running until you see the first panic error (should be printed on screen).
