### ISSUE TITLE
packetbeat logs http basic authentication "Authorization" header (username and password)

### ISSUE THREAD

**Issue by ntfrnzn** [packetbeat/packetbeat#93]
http basic authentication includes a base64-encoded Authorization header which often is just the plaintext username:password.   In the packetbeat logs, this appears in the "raw_request" and "headers.authorization" fields.  These should be removed from the message before logging it.

**Comment by ntfrnzn** [comment]
I've added a pull request which removes the sensitive data.  In my changes, the code and configuration is alongside the censor_password functionality.  I saw the comments in the other issue about the censoring being a bit hacky -- so my changes don't clean that up much at all.   But I think it still can be refactored in some straightforward way.

**Comment by tsg** [comment]
Thank you for the pull requests. I'll check it as soon as I have the chance.

**Comment by tsg** [comment]
Pull request merged.
