### ISSUE TITLE
ERROR: apt is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by leeyu01** [packetbeat/packetbeat#99]
Hi,

I have encountered with an installation error for all-in-one installation on a fresh new debian 7 64bit has been configured and updated completely.

Linux xsb-appmon 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux

ansible-playbook  -i hosts site.yml returned an error
ERROR: apt is not a legal parameter in an Ansible task or handler

My ansible-playbook version is blowl
ansible-playbook --version
ansible-playbook 1.9
  configured module search path = None
I'd appreciated on your input.

**Comment by tsg** [comment]
Seems like a problem with the ansible installation. How did you install ansible?

**Comment by leeyu01** [comment]
Yes, it looks like. I have compiled the source. 
the binary version, 1.84 works okay.

**Comment by homme** [comment]
I had this problem whilst using the source distribution.  It turned out I'd forgotten to update the git submodules:
```
git submodule update --init lib/ansible/modules/core
git submodule update --init lib/ansible/modules/extras
git submodule update --init v2/ansible/modules/core
git submodule update --init v2/ansible/modules/extras
```
